[collectors]

[collectors.geofence]

PATH = "micromobility.bolt.collectors.geofence.BoltGeofenceCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"

 
[collectors.vehicles_position]

PATH = "micromobility.bolt.collectors.vehicle_position.BoltVehiclePositionCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "51m"


[collectors.vehicle_type]

PATH = "micromobility.bolt.collectors.vehicle_type.BoltVehicleTypeCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"


[harvesters]

[harvesters.count]
PATH = "micromobility.bolt.harvesters.count.CountHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "15m"
SOURCE = "bolt.vehicles_position"
SOURCE_RANGE = "15m"
DEPENDENCIES = ["micromobility.area"]
DEPENDENCIES_LIMIT = [1]



[harvesters.daily_prediction]
PATH = "micromobility.harvesters.daily_predictor.DailyPredictorHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "00:00"
SOURCE = "bolt.count"
SOURCE_RANGE = "24h"
DEPENDENCIES = ["bolt.count"]
DEPENDENCIES_LIMIT = [100]
