[collectors]

[collectors.geofence]

PATH = "micromobility.dott.collectors.geofence.DottGeofenceCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"


[collectors.vehicles_position]

PATH = "micromobility.dott.collectors.vehicle_position.DottVehiclePositionCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "5m"


[collectors.vehicle_type]

PATH = "micromobility.dott.collectors.vehicle_type.DottVehicleTypeCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"


[harvesters]

[harvesters.count]
PATH = "micromobility.dott.harvesters.anomaly_detector.AnomalyHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "15m"
SOURCE = "dott.vehicles_position"
SOURCE_RANGE = "15m"
DEPENDENCIES = ["micromobility.area", "dott.daily_prediction", "dott.count"]
DEPENDENCIES_LIMIT = [1, 1, 100]



[harvesters.daily_prediction]
PATH = "micromobility.dott.harvesters.daily_predictor.DailyPredictorHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "00:00"
SOURCE = "dott.count"
SOURCE_RANGE = "24h"
DEPENDENCIES = ["dott.count"]
DEPENDENCIES_LIMIT = [100]
STORAGE_DATE = true


