[collectors]

[collectors.vehicles_position]

PATH = "micromobility.lime.collectors.vehicle_position.LimeVehiclePositionCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "5m"


[collectors.vehicle_type]

PATH = "micromobility.lime.collectors.vehicle_type.LimeVehicleTypeCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"


[harvesters]

[harvesters.count]
PATH = "micromobility.lime.harvesters.anomaly_detector.AnomalyHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "15m"
SOURCE = "lime.vehicles_position"
SOURCE_RANGE = "15m"
DEPENDENCIES = ["micromobility.area", "lime.daily_prediction"]
DEPENDENCIES_LIMIT = [1, 1]



[harvesters.daily_prediction]
PATH = "micromobility.lime.harvesters.daily_predictor.DailyPredictorHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "00:00"
SOURCE = "lime.count"
SOURCE_RANGE = "24h"
DEPENDENCIES = ["lime.count"]
DEPENDENCIES_LIMIT = [100]
STORAGE_DATE = true
