[collectors]

[collectors.geofence]

PATH = "micromobility.pony.collectors.geofence.PonyGeofenceCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"


[collectors.vehicles_position]

PATH = "micromobility.pony.collectors.vehicle_position.PonyVehiclePositionCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "5m"


[collectors.vehicle_type]

PATH = "micromobility.pony.collectors.vehicle_type.PonyVehicleTypeCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "01:00"



[harvesters]

[harvesters.count]
PATH = "micromobility.pony.harvesters.anomaly_detector.AnomalyHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "15m"
SOURCE = "pony.vehicles_position"
SOURCE_RANGE = "15m"
DEPENDENCIES = ["micromobility.area", "pony.daily_prediction", "pony.count"]
DEPENDENCIES_LIMIT = [1, 1, 100]



[harvesters.daily_prediction]
PATH = "micromobility.pony.harvesters.daily_predictor.DailyPredictorHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "00:00"
SOURCE = "pony.count"
SOURCE_RANGE = "24h"
DEPENDENCIES = ["pony.count"]
DEPENDENCIES_LIMIT = [100]
STORAGE_DATE = true

