[collectors]

[collectors.gtfs]

PATH = "de_lijn.collectors.gtfs.DeLijnGTFSStaticCollector"
DATA_FORMAT = "gtfs"
DATA_TYPE = "binary"
SCHEDULE = "05:00"

[collectors.gtfs_realtime]

PATH = "de_lijn.collectors.gtfs_realtime.DeLijnGTFSRealtimeCollector"
DATA_FORMAT = "gtfs_realtime"
DATA_TYPE = "binary"
SCHEDULE = "20s"

[collectors.bmc_gtfs_static]

PATH = "de_lijn.collectors.bmc_gtfs_static.DeLijnBMCGTFSStaticCollector"
DATA_FORMAT = "gtfs"
DATA_TYPE = "binary"
SCHEDULE = "05:00"

[collectors.bmc_gtfs_rt_alert]

PATH = "de_lijn.collectors.bmc_gtfs_rt_alert.DeLijnBMCGTFSRTAlertCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "1m"

[collectors.bmc_gtfs_rt_trip_update]

PATH = "de_lijn.collectors.bmc_gtfs_rt_trip_update.DeLijnBMCGTFSRTTripUpdateCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "20s"
