[collectors]

[collectors.gtfs]

PATH = "stib.collectors.gtfs.STIBGTFSCollector"
DATA_FORMAT = "gtfs"
DATA_TYPE = "binary"
SCHEDULE = "04:20"

[collectors.shapefile_raw]

PATH = "stib.collectors.shapefile.STIBShapeFilesCollector"
DATA_FORMAT = "shapefile"
DATA_TYPE = "binary"
SCHEDULE = "03:20"

[collectors.stops_by_line]

PATH = "stib.collectors.stops_by_line.STIBStopsByLineCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "00:20"

[collectors.stop_details]

PATH = "stib.collectors.stop_details.STIBStopDetailsCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "00:20"

[collectors.vehicle_distance]

PATH = "stib.collectors.vehicle_distance.STIBVehiclePositionsCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "20s"
PARQUETIZE = { BATCH = "1h", GROUPS = [{GROUP="1d"},{GROUP="1w", KEYS=["lineId"]},], SCHEMA = { type = "array", items = { type = "object", properties = { directionId = { type = "string" }, distanceFromPoint = { type = "integer" }, pointId = { type = "string" } } } } }

[collectors.travellers_information]

PATH = "stib.collectors.travellers_information.STIBTravellersInformationCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "15m"

[collectors.waiting_times]

PATH = "stib.collectors.waiting_times.STIBWaitingTimesCollector"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SCHEDULE = "20s"


[harvesters]

[harvesters.shapefile]

PATH = "stib.harvesters.shapefile_geojson.STIBShapefileGeoJSONHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SOURCE = "stib.shapefile_raw"

[harvesters.stops]

PATH = "stib.harvesters.stops.STIBStopsHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SOURCE = "stib.stops_by_line"
DEPENDENCIES = ["stop_details"]

[harvesters.segments]

PATH = "stib.harvesters.segments.STIBSegmentsHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SOURCE = "stib.shapefile"
DEPENDENCIES = ["stops"]

[harvesters.speed]
PATH = "stib.harvesters.speed.StibSegmentsSpeedHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SOURCE = "stib.vehicle_distance"
SOURCE_RANGE = 2
SOURCE_RANGE_STRICT = true

[harvesters.aggregated_speed]
PATH = "stib.harvesters.aggregated_speed.StibSegmentsAggregatedSpeedHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SOURCE = "stib.speed"
SOURCE_RANGE = 30
SOURCE_RANGE_STRICT = false
MULTIPLE_RESULTS = false

[harvesters.vehicle_position_geometry]

PATH = "stib.harvesters.vehicle_position_geometry.STIBVehiclePositionGeometryHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SOURCE = "stib.vehicle_distance"
DEPENDENCIES = ["segments", "stops"]


[harvesters.vehicle_identify]

PATH = "stib.harvesters.identify_vehicle.identify_vehicle.STIBVehicleIdentifyHarvester"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SOURCE = "stib.vehicle_position_geometry"
SOURCE_RANGE = 20
SOURCE_RANGE_STRICT = false
MULTIPLE_RESULTS = true
DEPENDENCIES = ["shapefile"]
DEPENDENCIES_LIMIT = [1]
OPTIONAL_DEPENDENCIES = ["vehicle_identify"]
OPTIONAL_DEPENDENCIES_LIMIT = [10]

[handlers]

[handlers.trips]

PATH = "stib.handlers.trips.STIBTripsHandler"
DATA_FORMAT = "mf-json"
DATA_TYPE = "json"
QUERY_PARAMETERS = { start_timestamp = "int", end_timestamp = "int" }